// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A multilingual chatbot that answers tourist questions about Jharkhand.
 *
 * - answerTouristQuestions - A function that answers tourist questions about Jharkhand in the user's preferred language.
 * - AnswerTouristQuestionsInput - The input type for the answerTouristQuestions function.
 * - AnswerTouristQuestionsOutput - The return type for the answerTouristQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerTouristQuestionsInputSchema = z.object({
  question: z.string().describe('The tourist question about Jharkhand.'),
  language: z.string().describe('The preferred language for the answer.'),
});
export type AnswerTouristQuestionsInput = z.infer<typeof AnswerTouristQuestionsInputSchema>;

const AnswerTouristQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the tourist question in the preferred language.'),
});
export type AnswerTouristQuestionsOutput = z.infer<typeof AnswerTouristQuestionsOutputSchema>;

export async function answerTouristQuestions(input: AnswerTouristQuestionsInput): Promise<AnswerTouristQuestionsOutput> {
  return answerTouristQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerTouristQuestionsPrompt',
  input: {schema: AnswerTouristQuestionsInputSchema},
  output: {schema: AnswerTouristQuestionsOutputSchema},
  prompt: `You are a multilingual chatbot providing information about Jharkhand to tourists.

  Answer the following question in the specified language:

  Question: {{{question}}}
  Language: {{{language}}}

  Answer:`, 
});

const answerTouristQuestionsFlow = ai.defineFlow(
  {
    name: 'answerTouristQuestionsFlow',
    inputSchema: AnswerTouristQuestionsInputSchema,
    outputSchema: AnswerTouristQuestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
